# references:
# Travis-CI - Python : https://docs.travis-ci.com/user/languages/python/

language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip3 install pylint

# command to run tests
script:
  - pylint *
  - python compile_files.py
  - pytest # or py.test for Python versions 3.5 and below
