# references:
# Travis-CI - Python : https://docs.travis-ci.com/user/languages/python/

language: python
python:
  - "3.8"

install:
  - pip3 install pipenv
  - pipenv install

script:
  - pylint *
  - python compile_files.py
  - pytest
